# Generated by Django 3.2.4 on 2021-06-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.BooleanField()),
                ('engine', models.CharField(choices=[('GAS', 'Газ'), ('BENZ', 'Бензин'), ('DIESEL', 'Дизель'), ('ELECTRO', 'Электро'), ('GAS_BENZ', 'Газ-Бензин')], max_length=255)),
                ('steering_wheel', models.CharField(choices=[('LEFT', 'Левый'), ('RIGHT', 'Правый')], max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_slug', models.CharField(max_length=255)),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salecars.city')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=12)),
                ('price_to', models.IntegerField(blank=True, null=True)),
                ('price_from', models.IntegerField(blank=True, null=True)),
                ('telegram_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salecars.auto')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salecars.region')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salecars.marks')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salecars.models'),
        ),
        migrations.AddField(
            model_name='auto',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salecars.region'),
        ),
    ]
